### ISSUE TITLE
1.18 Port

### ISSUE THREAD

**Issue by VulpesStella** [TartaricAcid/ExtraPlayerRenderer#6]
Can't wait to play mc1.18 live on bilibili with that cute fake live2D model, I tried to port the mod to 1.18.
I referenced some of the Vanilla codes and replaced a few functions without changing the structure of the code.
And now it seems to work :D
If you want, you can always create a new "1.18" branch and merge [this](https://github.com/FractalMC/ExtraPlayerRenderer/tree/1.18).
(hope it helps you save timeヾ(•ω•`)o)

**Comment by TartaricAcid** [comment]
I was too busy some time ago, recently updated 1.18
